---
- name: allocate an elastic IP and associtate it with the instance
  ec2_eip:
    device_id: '{{ ec2_data.tagged_instances[0].id }}'
    region: '{{ availRegion }}'
    release_on_disassociation: true
  register: eip_data