---
- name: Install nginx
  become: yes
  package:
    name: nginx
    state: installed

- name: Enable http
  become: yes
  firewalld:
    zone: public
    immediate: yes
    service: "{{ service_name }}"
    permanent: yes
    state: enabled

- name: copy the "nginx.conf" file
  become: yes
  template:
    src: "{{ nginx_file_path }}"
    dest: "{{ nginx_app_path }}"